# Copyright (C) 1993-1999 Ken'ichi Fukamachi
#          All rights reserved. 
#               1993-1996 fukachan@phys.titech.ac.jp
#               1996-1999 fukachan@sapporo.iij.ad.jp
# 
# FML is free software; you can redistribute it and/or modify
# it under the terms of GNU General Public License.
# See the file COPYING for more details.
#
# $Id$
#

SUBDIRS += MIME
SUBDIRS += utilities
SUBDIRS += www
SUBDIRS += traffic
SUBDIRS += localhack/release-1/Elena
SUBDIRS += localhack/release-1/mnews
SUBDIRS += localhack/release-1/putfiles
SUBDIRS += localhack/release-1/schwalben
SUBDIRS += localhack/release-2/kizu
SUBDIRS += localhack/release-2/doc-changes
SUBDIRS += localhack/release-2/mnews
SUBDIRS += localhack/release-2/member_name
SUBDIRS += lexical
SUBDIRS += pager
SUBDIRS += mail2fax
SUBDIRS += netutils
SUBDIRS += mail2news
SUBDIRS += msend-anytime
SUBDIRS += irc

.include "../distrib/mk/fml.contrib.mk"
