#
# $Id$
#

DOC_EXAMPLES_SUBDIR  += virtual

# fml misc virtual
DOC_EXAMPLES_SOURCES += virtual/virtual-domain
DOC_EXAMPLES_SOURCES += virtual/fml-install-for-virtual-domain

# 
# DOC_EXAMPLES_RAW_SOURCES += virtual/
DOC_EXAMPLES_RAW_SOURCES += virtual/postfix-example.txt

