# Copyright (C) 1993-1999 Ken'ichi Fukamachi
#          All rights reserved. 
#               1993-1996 fukachan@phys.titech.ac.jp
#               1996-1999 fukachan@sapporo.iij.ad.jp
# 
# FML is free software; you can redistribute it and/or modify
# it under the terms of GNU General Public License.
# See the file COPYING for more details.
#
# $Id$
#

SOURCES = FILES libtraffic.help libtraffic.install traffic.help VER_UP

TARGET_DIR = ${CONTRIB_DIR}/traffic

.include "$(FML)/distrib/mk/fml.contrib.mk"
