DOC_EXAMPLES_SOURCES += postfix-install
DOC_EXAMPLES_SOURCES += fml-install
DOC_EXAMPLES_SOURCES += config-default 
DOC_EXAMPLES_SOURCES += config-auto-subscribe 
DOC_EXAMPLES_SOURCES += config-asymmetric-regist 
DOC_EXAMPLES_SOURCES += config-remote
DOC_EXAMPLES_SOURCES += config-moderated 
DOC_EXAMPLES_SOURCES += setup-more-secure 
DOC_EXAMPLES_SOURCES += config-post-from-anyone
DOC_EXAMPLES_SOURCES += howto-customize
DOC_EXAMPLES_SOURCES += errormail-handling

# samples
DOC_EXAMPLES_SAMPLES += sample.aliases
DOC_EXAMPLES_SAMPLES += sample.include
DOC_EXAMPLES_SAMPLES += sample.include-ctl
DOC_EXAMPLES_SAMPLES += sample.ls_elena
DOC_EXAMPLES_SAMPLES += sample.ls_fml
