# Copyright (C) 1993-1999,2001 Ken'ichi Fukamachi
#          All rights reserved. 
#               1993-1996 fukachan@phys.titech.ac.jp
#               1996-1999,2001 fukachan@sapporo.iij.ad.jp
# 
# FML is free software; you can redistribute it and/or modify
# it under the terms of GNU General Public License.
# See the file COPYING for more details.
#
# $FML$
#

SOURCES = README Rmail2fml.pl babyl2mh filter my-mh-post my-mh-post.pl packmbox.pl rmail2mbox.el scan.format stardate.el lntgz.pl

TARGET_DIR = ${CONTRIB_DIR}/utilities

.include "$(FML)/distrib/mk/fml.contrib.mk"
