#!/bin/sh
#
# $Id$
#
trap "rm -f __*__ /tmp/fml$$" 0 1 3 15

cat > /tmp/fml$$ << __EOF__
Bourne shell(大抵は/bin/sh)がうまく動かないみたいだねぇ
これはだめだわ
__EOF__

export PATH || cat /tmp/fml$$
rm -f /tmp/fml$$

rows=24
rows=`expr $rows - 1`
which=0
com='n'

while [ $# -gt 0 ]
do
    case $1 in
    -l )
	shift
	rows=$1
	;;
     * )	
	echo "$1 is not matched option"
	exit 2
    esac
    shift
done

while [ "$com" != 'q' ]
do
	# Status
	case $com in
	   r  )
		X="ShowPage $rows 1"
		;;
	   n | "" )
		which=`expr $which + 1`
		X="ShowPage $rows $which"
		;;
	   p )
		which=`expr $which - 1`
		X="ShowPage $rows $which"
		;;
	   q )
		 X=q
		;;
	   [0-9]* )
		 X="URL $com"
		;;
	   * )
		 X=o
		;;
	esac

	echo $X| perl WWWMail.pl

	# COMMAND LINE
	echo    "--------------------------------------------- "
	echo -n "Quit[q], Reset[r], Prev[p], Next or Return[n] "; read com

	# Transform for convenience
	com=`echo $com| tr A-Z a-z`
	echo ": $com"	
done


exit 0;
