#!/bin/sh
#
# $Id$
# Original file is using EUC
# あ〜あ、エレガントじゃないなぁ、このコード
#
trap "rm -f __*__ /tmp/fml$$" 0 1 3 15

ML="fml-test@phys.titech.ac.jp"

cat > /tmp/fml$$ << __EOF__
Bourne shell(大抵は/bin/sh)がうまく動かないみたいだねぇ
これはだめだわ
__EOF__

export PATH || cat /tmp/fml$$
rm -f /tmp/fml$$

HELP="/tmp/fml$$"
cat > $HELP << __EOF__
HELP MESSAGE( fml remote controling script )

# admin command
commands are follows:
	add 
	addadmin 
	addpriv 
	bye 
	byeadmin 
	byepriv 
	dir 
	get 
	help 
	log 
	ls 
	off 
	on 
	put 
	remove
	rename
__EOF__

echo ""	
echo "		fml remote controling script		"
echo "		#RemoteControl for $ML O.K.?"	
echo ""	
echo ""	

while [ $# -gt 0 ]
do
    case $1 in
    -h )
	cat $HELP;
	exit 0;
	;;
     * )	
	echo "put [q] if you exit"	
	;;
    esac
    shift
done

# MAIN
# COMMAND LINE
echo    "--------------------------------------------- "
echo -n "Quit: [q], Help: [h] or Return INPUT> "; read com

# Transform for convenience
com=`echo $com| tr A-Z a-z`
echo ": $com"	

while [ "$com" != 'q' ]
do
	# Status
	case $com in
	   add | addadmin | addpriv | bye | byeadmin | byepriv | dir | get | help | log | ls | off | on | put | remove | rename )
		echo "# admin $com | mail -v $ML"
	#	echo "# admin $com"| mail -v $ML
		;;
	   h )
		cat $HELP
		;;
	   q )
		 X=q
		;;
	   * )
		cat $HELP
		;;
	esac

	# COMMAND LINE
	echo    "--------------------------------------------- "
	echo -n "Quit: [q], Help: [h] or Return INPUT> "; read com

	# Transform for convenience
	com=`echo $com| tr A-Z a-z`
	echo ": $com"	
done

exit 0
