.include "../../distrib/mk/fml.pkg.mk"

MASTER_SITE  = http://www.cpan.org/modules/by-module/

PKGNAME      = MD5
#DISTNAME    = MD5-1.7.tar.gz
DISTNAME     = Digest-MD5-2.07.tar.gz

EXTRACT      = yes

PERL_MODULE  = yes
COMPILE_DIR  = Digest-MD5-2.07

.include "../../distrib/mk/fml.pkgsubr.mk"
