.\" Copyright (C) 1993-1999 Ken'ichi Fukamachi
.\"          All rights reserved. 
.\"               1993-1996 fukachan@phys.titech.ac.jp
.\"               1996-1999 fukachan@sapporo.iij.ad.jp
.\" 
.\" FML is free software; you can redistribute it and/or modify
.\" it under the terms of GNU General Public License.
.\" See the file COPYING for more details.
.\"
.\" $Id$
.\"
.Dd April 3, 1999
.Dt FML 8
.Os
.Sh NAME
.Nm fml
.Nd mailing list server/driver package
.Sh DESCRIPTION
.Sy fml
is the package name of 
.Sy mailing list
server/driver package. 
It contains 
distributor, 
mailing list manager
and  
CUI (Character User Interface) control program
.Sy makefml
.

.Sh FML DOCUMENTS
.Pp
For more details, please see documents installed under 
.Sy _EXEC_DIR_/doc/
.
.
Plain texts are in
.Sy _EXEC_DIR_/doc/
but
the HTML version documents are also in
.Sy _EXEC_DIR_/doc/html/
.

You can see the latest information on
.Sy http://www.fml.org/
.

.Pp
.Sh SEE ALSO
.Xr makefml 1
.Sh AUTHOR
Ken'ichi Fukamachi <fukachan@fml.org>
.Sh HISTORY
The first official release is 
.Sy fml 1.2 
, which was submitted to fj.sources in 1994.
