DOC_DEVEL_INDEX   += index.html index-e.html

DOC_DEVEL_SOURCES += apache-ssl.txt
DOC_DEVEL_SOURCES += apache+mod_ssl.txt
DOC_DEVEL_SOURCES += qmail-users-assign.txt
DOC_DEVEL_SOURCES += openssl.txt
DOC_DEVEL_SOURCES += qmail-internal.txt
DOC_DEVEL_SOURCES += bind-version.txt
DOC_DEVEL_SOURCES += OS_and_Perl.txt
