#!/usr/local/bin/perl --    # -*-Perl-*-
# Copyright (C) 1993-1996 fukachan@phys.titech.ac.jp
# Copyright (C) 1996-1998 fukachan@sapporo.iij.ad.jp
# fml is free software distributed under the terms of the GNU General
# Public License. see the file COPYING for more details.

# require 'libfml.pl';

open(TTY, "< /dev/tty") || die $!;

print STDERR "> ";
while (<TTY>) {
    print STDERR "> ";
    &Command($_);
    last if eof;
}



1;

sub Command 
{
    local($_) = @_;
    print "\nINPUT>$_\n";
}

