#!/bin/sh
# Copyright (C) 1993-1996 fukachan@phys.titech.ac.jp
# Copyright (C) 1996-1998 fukachan@sapporo.iij.ad.jp
# fml is free software distributed under the terms of the GNU General
# Public License. see the file COPYING for more details.

file=`basename $1`

rm -f $file.4
mv -f $file.3	$file.4
mv -f $file.2	$file.3
mv -f $file.1	$file.2
mv -f $file.0	$file.1
mv -f $file.bak $file.0

exit 0

