TUTORIAL_BASIC_SOURCES += postfix-install
TUTORIAL_BASIC_SOURCES += fml-install
TUTORIAL_BASIC_SOURCES += server_movement
TUTORIAL_BASIC_SOURCES += config-default 
TUTORIAL_BASIC_SOURCES += config-auto-subscribe 
TUTORIAL_BASIC_SOURCES += config-asymmetric-regist 
TUTORIAL_BASIC_SOURCES += config-remote
TUTORIAL_BASIC_SOURCES += config-moderated 
TUTORIAL_BASIC_SOURCES += setup-more-secure 
TUTORIAL_BASIC_SOURCES += config-post-from-anyone
TUTORIAL_BASIC_SOURCES += howto-customize
TUTORIAL_BASIC_SOURCES += site_xxx
TUTORIAL_BASIC_SOURCES += errormail-handling
TUTORIAL_BASIC_SOURCES += errormail-handling-qmail
TUTORIAL_BASIC_SOURCES += files
TUTORIAL_BASIC_SOURCES += installer-QandA
TUTORIAL_BASIC_SOURCES += QandA

# samples
TUTORIAL_BASIC_SAMPLES += sample.aliases
TUTORIAL_BASIC_SAMPLES += sample.include
TUTORIAL_BASIC_SAMPLES += sample.include-ctl
TUTORIAL_BASIC_SAMPLES += sample.ls_elena
TUTORIAL_BASIC_SAMPLES += sample.ls_fml
TUTORIAL_BASIC_SAMPLES += sample.add

# install index.html
TUTORIAL_BASIC_SAMPLES += index.html
TUTORIAL_BASIC_SAMPLES += MTAspecific.html
TUTORIAL_BASIC_SAMPLES += newml.html
TUTORIAL_BASIC_SAMPLES += add.html
TUTORIAL_BASIC_SAMPLES += bye.html
TUTORIAL_BASIC_SAMPLES += acl.html


