.include "../../distrib/mk/fml.pkg.mk"

MASTER_SITE  = ftp://ftp.iij.ad.jp/pub/IIJ/dist/utashiro/perl/
# PKGNAME      = jcode

DISTNAME     = jcode.pl-2.11
DIST_NEWNAME = jcode.pl

.include "../../distrib/mk/fml.pkgsubr.mk"
