.include "../../distrib/mk/fml.pkg.mk"

PKGNAME      = traffic
DISTNAME     = libtraffic1.1.tar.gz
EXTRACT      = yes

.include "../../distrib/mk/fml.pkgsubr.mk"

link: libtraffic.pl

libtraffic.pl: work/traffic/libtraffic.pl
	ln work/traffic/libtraffic.pl libtraffic.pl
