# Copyright (C) 2000 Ken'ichi Fukamachi
#          All rights reserved. 
#
# $Id$
# $NetBSD$
# $FML$
#

DOC_MULTIVIEW_HTML  = index download anoncvs search
DOC_MULTIVIEW_HTML += menu menubar virus_check treking_guide
DOC_MULTIVIEW_HTML += booknotes
DOC_MULTIVIEW_HTML += booktypo
