#
# $Id$
#

DOC_EXAMPLES_SUBDIR  += tips

# fml misc tips
DOC_EXAMPLES_SOURCES += tips/virtual-domain
DOC_EXAMPLES_SOURCES += tips/recruit
DOC_EXAMPLES_SOURCES += tips/fml-stable-with-cgi
DOC_EXAMPLES_SOURCES += tips/misc
DOC_EXAMPLES_SOURCES += tips/qmail-mead
DOC_EXAMPLES_SOURCES += tips/nospam

# server tips
DOC_EXAMPLES_SOURCES += tips/postfix-pop-before-smtp
DOC_EXAMPLES_SOURCES += tips/smrsh

# virtual domain tips
DOC_EXAMPLES_SOURCES += tips/fml-install-for-virtual-domain

# obsolete
DOC_EXAMPLES_SOURCES += tips/distribute-emulation

DOC_EXAMPLES_RAW_SOURCES += tips/qpopper-patch-by-drac.txt
DOC_EXAMPLES_RAW_SOURCES += tips/myGenConfirmReplySubject.pl
DOC_EXAMPLES_RAW_SOURCES += tips/dot_xxxxshell_rc

