DOC_EXAMPLES_SUBDIR  += tips

# fml misc tips
DOC_EXAMPLES_SOURCES += tips/virtual-domain
DOC_EXAMPLES_SOURCES += tips/recruit
DOC_EXAMPLES_SOURCES += tips/fml-stable-with-cgi
DOC_EXAMPLES_SOURCES += tips/misc
DOC_EXAMPLES_SOURCES += tips/qmail-mead

# server tips
DOC_EXAMPLES_SOURCES += tips/postfix-pop-before-smtp
DOC_EXAMPLES_SOURCES += tips/smrsh

DOC_EXAMPLES_RAW_SOURCES += tips/qpopper-patch-by-drac.txt
