#!/bin/sh

buf=/tmp/trans$$

trap "rm -f $buf" 0 1 3 15


lynx -dump http://www.nic.ad.jp/jp/regist/dom/or-ne/lists/trans.html \
> $buf
nkf -e $buf | egrep '²ÄÇ½' |\
perl -nle 's/(\S+\.OR\.JP)\s+(\S+\.NE\.JP)/printf "%-30s  %s\n", $1, $2/e'|\
sort |\
tr 'A-Z' 'a-z'

exit 0
